monolog:
    channels: ['security', 'auth']
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event', '!security', '!auth'] # Exclure les canaux spécifiques
        security:
            type: stream
            path: '%kernel.logs_dir%/security.log'
            level: debug
            channels: ['security']
        auth:
            type: stream
            path: '%kernel.logs_dir%/auth.log'
            level: debug
            channels: ['auth']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
