security:
  providers:
    github_user_provider:
      id: App\Security\GithubUserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    public:
      pattern: ^/$
      security: false

    main:
      lazy: true
      provider: github_user_provider
      custom_authenticators:
        - App\Security\GithubAuthenticator
      logout:
        path: /logout
        target: /
      stateless: false

  access_control:
    - { path: ^/$, roles: PUBLIC_ACCESS }
    - { path: ^/connect/github, roles: PUBLIC_ACCESS }
    - { path: ^/login/github/check, roles: PUBLIC_ACCESS }
    - { path: ^/profile, roles: ROLE_USER }
    - { path: ^/all_projects, roles: ROLE_USER }