services:
  app:
    build: .
    environment:
      APP_ENV: dev
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal
      DATABASE_URL: mysql://root:Ilomilo4002@database:3306/centrale
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Ilomilo4002
      MYSQL_DATABASE: centrale
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  mailer:
    image: mailhog/mailhog
    container_name: symfony_mailer
    ports:
      - "8025:8025"

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

volumes:
  db_data:
