home:
    path: /
    controller: App\Controller\GithubController::home

connect_github:
    path: /connect/github
    controller: App\Controller\GithubController::connectGithub

login_github_check:
    path: /login/github/check
    controller: App\Controller\GithubController::loginGithubCheck
    
deploy_version:
    path: /deploy/{name}/{version}
    controller: App\Controller\GithubController::deployVersion
    methods: [POST]
    requirements:
        name: ".+"
        version: ".+"
